---
ngi_pipeline_repo: https://github.com/NationalGenomicsInfrastructure/ngi_pipeline.git
ngi_pipeline_dest: "{{ sw_path }}/ngi_pipeline"
ngi_pipeline_version: 77a8749e618b6e72f34a0015de77ff97abd463e0

ngi_pipeline_log: "{{ ngi_log_path }}/ngi_pipeline.log"
ngi_pipeline_db_path: "{{ ngi_pipeline_path }}/db"
ngi_pipeline_db: "{{ ngi_pipeline_db_path }}/records_db.sql"
ngi_pipeline_config: miarka_ngi_config_{{ site }}.yaml
rna_seq_conf: "{{ ngi_pipeline_conf }}/rnaseq_{{ site }}.config"
bash_env_site_script: sourceme_site.sh

piper_module_version: 1.5.1
gatk_bundle_b37: "{{ reference_data_dir }}/piper_references/2016-04-07/gatk_bundle/2.8/b37/"
igenomes_path: "{{ reference_data_dir }}/igenomes"

gatk_key: pontus.larsson_medsci.uu.se.key
charon_base_url: https://charon-dev.scilifelab.se

ngi_pipeline_deliverables:
  -
    - DELIVERY.README.txt
  -
    - "{{ 'ACKNOWLEDGEMENTS_' ~ site | capitalize | first ~ '.txt' }}"
    - ACKNOWLEDGEMENTS.txt
